package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, 21 May, 2023 5:08:10 PM IST
*/

public interface CalculatorOperations 
{
  float getSum (float a, float b);
  float getSub (float a, float b);
  float getProduct (float a, float b);
  float getQuotient (float a, float b) throws CalculatorApp.CalculatorPackage.DivisionByZero;
} // interface CalculatorOperations
